version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pst'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dbuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'dbus3r'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 's@pI3nt'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-pst:/var/lib/mysql
# Names our volume
volumes:
  mysql-pst: