# Server configurations
server:
  port: 8080


# Logging configurations
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
      
# Spring application configurations
spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/pst
    username: dbuser
    password: dbus3r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
# Pagination settings
spring.data.web:
  pageable:
    default-page-size: 10
    max-page-size: 1000
    
    